### ISSUE TITLE
Sorry, I've got the following error trying to start the development server:

### ISSUE THREAD

**Issue by sbucek** [campbel/gae-ng-seed#1]
The Go application could not be built.

(Executed command: /home/nox/Apps/go_appengine/goroot/bin/go-app-builder -app_base /home/nox/workspace/goapp -arch 6 -dynamic -goroot /home/nox/Apps/go_appengine/goroot -nobuild_files ^^$ -unsafe -gopath /home/nox/go -binary_name _go_app -extra_imports appengine_internal/init -work_dir /tmp/tmpE97_wgappengine-go-bin -gcflags -I,/home/nox/Apps/go_appengine/goroot/pkg/linux_amd64_appengine -ldflags -L,/home/nox/Apps/go_appengine/goroot/pkg/linux_amd64_appengine server/api/xsrf_middleware.go server/server.go server/api/api.go server/xsrf.go)
/tmp/tmpE97_wgappengine-go-bin/server/api/xsrf_middleware.go:15: undefined: gore.Request
/tmp/tmpE97_wgappengine-go-bin/server/api/xsrf_middleware.go:15: undefined: gore.Response

2015/04/25 20:29:37 go-app-builder: build timing: 4×6g (91ms total), 0×gopack (0 total), 0×6l (0 total)
2015/04/25 20:29:37 go-app-builder: failed running 6g: exit status 1

**Comment by campbel** [comment]
Should be fixed now.
